### ISSUE TITLE
Pink Logo 

### ISSUE THREAD

**Issue by tigerlampe** [xXBJXx/ioBroker.e-control-at-fuel#1]
bitte bei 
PINK - so pink so clever
und 
PINK Sparen beim Fahren 

logo hinzufügen in der anlage 
![Pink](https://user-images.githubusercontent.com/43344649/82484519-4e929a00-9ada-11ea-9adc-acfb2eb40df7.png)

**Comment by xXBJXx** [comment]
Station PINK + logo hinzugefügt bitte von github neu installieren
