### ISSUE TITLE
has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Negalein** [xXBJXx/ioBroker.e-control-at-fuel#156]
`State "e-control-at-fuel.0.ried_diesel.station_9.openingHours.Freitag" has no existing object, this might lead to an error in future versions`

Adapter 0.1.1
mit JS-Controller 3.3.14
und Admin 5.1.9

**Comment by xXBJXx** [comment]
Ich werde die weiter Entwicklung des Adapters Einstellen da es bereits ein 2ten Adapter dafür gibt [ioBroker.fuelpricemonitor](https://github.com/HGlab01/ioBroker.fuelpricemonitor) und ich nicht will das es mehrere adapter die das selbe tun gibt werde ich die Entwicklung Einstellen.
